name: Build and Push Docker Images

on:
  push:
    paths:
      - 'docker-files/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian
          - nginx
          - redis
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.image }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image with dynamic tags
      - name: Build Docker Image
        run: |
          TAG=$(date +%Y%m%d-%H%M%S)
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:$TAG \
            docker-files/${{ matrix.image }}

      # Push the Docker image
      - name: Push Docker Image
        run: |
          TAG=$(date +%Y%m%d-%H%M%S)
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:$TAG
